name: ChenYFanのHexoBlogBuild
'on':
  - workflow_dispatch
  - push
jobs:
  buildstatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install & Build
        run: >
          npm install -g hexo-cli

          npm i

          # Restore last modified time

          git ls-files -z | while read -d '' path; do touch -d "$(git log -1
          --format="@%ct" "$path")" "$path"; done

          hexo g

          curl -H 'Content-Type:text/plain' --data-binary
          @./public/baidu_urls.txt
          "http://data.zz.baidu.com/urls?site=https://blog.cyfan.top&token=${{
          secrets.BD_TOKEN }}"

          rm -rf ./public/CNAME

          echo "blog.cyfan.top" >> ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_GRASS_05AA38100 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "public" # App source code path
          skip_app_build: true
          skip_api_build: true
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM }}

      - name: Refresh NPM Cache
        run: >
          curl -X PUT "https://registry.npmmirror.com/chenyfan-blog/sync?publish=false&nodeps=false"
